#!/bin/sh

commit_msg=$(cat "$1")

pattern="^(feat|fix|refactor|perf|style|test|docs|build|ci|ops|chore|revert)(\(.+\))?: .+"

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
    echo
    echo "❌ Mensagem de commit inválida!"
    echo "Formato esperado:"
    echo "  tipo(escopo?): descrição"
    echo
    echo "Exemplos:"
    echo "  feat(api): add user endpoint"
    echo "  fix(auth): handle null token"
    echo "  docs(readme): update section"
    echo
    exit 1
fi
